name: test-sonar CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: >
        ./mvnw clean verify
        sonar:sonar
        -Pcoverage
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=amrsamii
        -Dsonar.projectKey=amrsamii_test-sonar
        -Dsonar.scm.disabled=True
        -Dsonar.pullrequest.github.repository=test690/test-sonar
        -Dsonar.pullrequest.key=3
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
